### ISSUE TITLE
[feat request]: add types

### ISSUE THREAD

**Issue by shunkakinoki** [linkstrifer/react-rough-notation#1]
Thanks for this awesome wrapper project!
Right now, types are not loaded in the IDE,
so adding types would be nice!

**Comment by linkstrifer** [comment]
Going to check this, thanks for reporting it

**Comment by linkstrifer** [comment]
This is in v0.0.6, thanks to @franky47

@shunkakinoki let me know if isn't working, here works as expected

**Comment by shunkakinoki** [comment]
Working perfectly!!! Thanks for the fix!!! Love the lib!!!
