### ISSUE TITLE
React-rough-notation not working with gatsby-build 

### ISSUE THREAD

**Issue by marieqg** [linkstrifer/react-rough-notation#11]
**Describe the bug**
I want to use react-rough-notation with gatsby.js. It works fine in development but when I build it's throwing an error. It's because how gatsby works and its lifecycle. 

<img width="1184" alt="Screen Shot 2020-07-23 at 12 42 52" src="https://user-images.githubusercontent.com/48214496/88244599-61973580-cce8-11ea-9521-efb7e0ff1c1d.png">

It's the following case: 
https://www.gatsbyjs.org/docs/debugging-html-builds/:

> Some of your code references “browser globals” like window or document. If this is your problem you should see an error above like “window is not defined”. To fix this, find the offending code and either a) check before calling the code if window is defined so the code doesn’t run while Gatsby is building (see code sample below) or b) if the code is in the render function of a React.js component, move that code into a componentDidMount lifecycle or into a useEffect hook, which ensures the code doesn’t run unless it’s in the browser. 

**To Reproduce**
Just use it in a gatsby website, and try to build.

**Desktop **
 - OS: 10.15.4 
 - Browser chrome
 - Gatsby CLI version: 2.11.5

**Additional context**
I managed to fix the problem by going to main.js and changing the following: 
`  var element = React.useRef(document.createElement("span")); `
into :
 ``const getElement = ()=>{
        if(typeof window !== `undefined`){
            return React.useRef(document.createElement("span"));
        } else {
             return null 
        }
    }
    var element = getElement()``

I've never done this before, so I was not too sure if I should do a bug report or a PR :)

**Comment by linkstrifer** [comment]
Hi @marieqg , can you tell me which version of ReactRoughNotation are you using?

**Comment by marieqg** [comment]
Hi @linkstrifer , I'm using "react-rough-notation": "^0.1.0"

**Comment by linkstrifer** [comment]
We resolved this issue in 0.1.1, try updating it, the fix was exactly what you did so you were right, let me know if it works

**Comment by marieqg** [comment]
You're rigth ! Updating it fixed the issue. sorry for the bother !

**Comment by linkstrifer** [comment]
Don't worry about it :D, the point is to make it work everywhere and better so let me know if you find something else, I'll close this one

**Comment by linkstrifer** [comment]
Fixed in 7382fd0
