### ISSUE TITLE
Type error when using from typescript

### ISSUE THREAD

**Issue by baldoalessandro** [linkstrifer/react-rough-notation#15]
**Describe the bug**
Using the snippet from docs in a typescript project results in:

```jsx
<RoughNotation type="underline" show={true}>
        Hello RoughNotation
 </RoughNotation>
```
```
Type '{ children: string; type: string; show: boolean; }' is not assignable to type 'IntrinsicAttributes & { children?: ReactNode; }'.
  Property 'type' does not exist on type 'IntrinsicAttributes & { children?: ReactNode; }'.ts(2322)
```

**To Reproduce**
I've created a code sandbox with the error I'm getting: https://codesandbox.io/s/unruffled-booth-892zc?file=/src/App.tsx

**Workaround**
I've changed `/dist/RoughNotation/RoughNotation.d.ts` to:

```ts
--- declare const RoughNotation: React.FunctionComponent;
+++ declare const RoughNotation: React.FunctionComponent<RoughNotationProps>;

```
and the type error disappeared but I don't know if there are other ways to fix this.

**Package versions**:
- react-rough-notation@1.0.0
- react@17.0.1
- react-dom@17.0.1
- typescript@4.1.2

Thank you for this project!

**Comment by linkstrifer** [comment]
Thanks for the report, I did the same you did but in the source files so basically you fix it xD

Here is your sandbox with the new version (1.0.1), not is working as expected:

https://codesandbox.io/s/gifted-sid-4pdv3?file=/src/App.tsx
