### ISSUE TITLE
feat: gatsby support

### ISSUE THREAD

**Issue by eric-hc** [linkstrifer/react-rough-notation#2]
Is there any way we could get support for frameworks such as Gatsby? Using this module worked locally, but when building pages for production, `document` was not found, assuming because of the way the DOM/HTML is built and not having `document` used by rough-notation

**Comment by eric-hc** [comment]
Also thinking this is out of scope for this repo, and might have to be a Gatsby plugin or separate project.

**Comment by ncthbrt** [comment]
@eric-hc: I created my own bindings for gatsby in an internal project. Had to modify it a little, so could share, but my implementation looked something like this: 

```typescript
function AnnotatedSpan({ annotationConfig, ...props }: React.DetailedHTMLProps<React.HTMLAttributes<HTMLSpanElement>, HTMLSpanElement> & { annotationConfig: RoughAnnotationConfig }) {
    const ref = useRef<HTMLSpanElement>(null);
    React.useLayoutEffect(() => {
        if (ref.current) {
            let annotation: RoughAnnotation | null = null;


                function annotateThis() {
                    annotation?.hide();
                    annotation = annotate(ref.current!, { animate: false, ...(annotationConfig ?? {}) });
                    annotation.show();
                }
                if (ref.current) {
                    annotateThis();
                    ref.current.addEventListener('onresize ', annotateThis);
                }

            return () => {
                annotation?.hide();

            }
        } else {
            return () => { };
        }
    }, [ref.current, annotationConfig]);

    return <span ref={ref} {...props} style={{ ...(props.style ?? {}), whiteSpace: 'nowrap' }} />;
}
```

**Comment by linkstrifer** [comment]
Mmmm sounds like is something related to rough-notation itself, I'm not using document anywhere, I'm going to check out and open a pull request if can fix it

> Is there any way we could get support for frameworks such as Gatsby? Using this module worked locally, but when building pages for production, `document` was not found, assuming because of the way the DOM/HTML is built and not having `document` used by rough-notation

**Comment by linkstrifer** [comment]
> @eric-hc: I created my own bindings for gatsby in an internal project. Had to modify it a little, so could share, but my implementation looked something like this:
> 
> ```ts
> function AnnotatedSpan({ annotationConfig, ...props }: React.DetailedHTMLProps<React.HTMLAttributes<HTMLSpanElement>, HTMLSpanElement> & { annotationConfig: RoughAnnotationConfig }) {
>     const ref = useRef<HTMLSpanElement>(null);
>     React.useLayoutEffect(() => {
>         if (ref.current) {
>             let annotation: RoughAnnotation | null = null;
> 
> 
>                 function annotateThis() {
>                     annotation?.hide();
>                     annotation = annotate(ref.current!, { animate: false, ...(annotationConfig ?? {}) });
>                     annotation.show();
>                 }
>                 if (ref.current) {
>                     annotateThis();
>                     ref.current.addEventListener('onresize ', annotateThis);
>                 }
> 
>             return () => {
>                 annotation?.hide();
> 
>             }
>         } else {
>             return () => { };
>         }
>     }, [ref.current, annotationConfig]);
> 
>     return <span ref={ref} {...props} style={{ ...(props.style ?? {}), whiteSpace: 'nowrap' }} />;
> }
> ```

This looks like what I did with this wrapper, did you do something to use annotationGroup? Is in my TODO list and I'm looking how to do it with a cool API or syntax

**Comment by franky47** [comment]
This is not limited to Gatsby, it's a general server-side rendering issue (I have the same error with Next.js).

This raises the question of what should be SSR'd ? This would depend on the `show` and `animate` props. Obviously the server cannot animate anything, so:
- `show === true && animate === false` => render the fully finished annotation
- all other cases: render no annotation, and let hydration do the animation/showing.

Here is my workaround for the moment:
```tsx
export const Annotation = ({ children, ...props }) => {
  const [hydrated, setHydrated] = React.useState(false)
  React.useEffect(() => setHydrated(true), [])

  if (!hydrated) {
    return children
  }
  return <RoughNotation {...props}>{children}</RoughNotation>
}
```

**Comment by ncthbrt** [comment]
> > @eric-hc: I created my own bindings for gatsby in an internal project. Had to modify it a little, so could share, but my implementation looked something like this:
> > 
> > ```ts
> > function AnnotatedSpan({ annotationConfig, ...props }: React.DetailedHTMLProps<React.HTMLAttributes<HTMLSpanElement>, HTMLSpanElement> & { annotationConfig: RoughAnnotationConfig }) {
> >     const ref = useRef<HTMLSpanElement>(null);
> >     React.useLayoutEffect(() => {
> >         if (ref.current) {
> >             let annotation: RoughAnnotation | null = null;
> > 
> > 
> >                 function annotateThis() {
> >                     annotation?.hide();
> >                     annotation = annotate(ref.current!, { animate: false, ...(annotationConfig ?? {}) });
> >                     annotation.show();
> >                 }
> >                 if (ref.current) {
> >                     annotateThis();
> >                     ref.current.addEventListener('onresize ', annotateThis);
> >                 }
> > 
> >             return () => {
> >                 annotation?.hide();
> > 
> >             }
> >         } else {
> >             return () => { };
> >         }
> >     }, [ref.current, annotationConfig]);
> > 
> >     return <span ref={ref} {...props} style={{ ...(props.style ?? {}), whiteSpace: 'nowrap' }} />;
> > }
> > ```
> 
> This looks like what I did with this wrapper, did you do something to use annotationGroup? Is in my TODO list and I'm looking how to do it with a cool API or syntax 

I didn't need animation, but if I did, I would probably have take a look at the react context API.

My approach would be to create a wrapper around an annotation group context provider.

Can have the annotation component use the annotation context and add to the group if the context is non null.

**Comment by linkstrifer** [comment]
@ncthbrt thanks for the idea, I did use context API for annotation group

@franky47 do you think using your workaround for a new component (aka, serverSideWrapper) for people who need this using server-side rendering is a good idea?

**Comment by franky47** [comment]
My workaround only works for cases where the annotation is to be animated on the client, it does not solve static annotations fully rendered on the server (when `animate: false, show: true`).

Unfortunately there is no easy way to do this but use the Generators from Rough.js, to ensure consistent rehydration (the randomness used has to be the same on the server and the client to avoid the annotation to change on rehydration, see [The Perils of Rehydration](https://joshwcomeau.com/react/the-perils-of-rehydration/)).

**Comment by pom421** [comment]
I have made a wrapper of `rough-notation` for Next.js for my usage which seems to correctly work : 

````js
import React, { useRef, useEffect } from "react"
import PropTypes from "prop-types"
import { annotate } from "rough-notation"

const RoughNotationWrapper = ({
  children,
  type = "highlight",
  color = "orange",
  animate = true,
  animationDuration = 1000,
  ...config
}) => {
  const ref = useRef(null)

  useEffect(() => {
    const annotation = annotate(ref.current, {
      type,
      color,
      animationDuration,
      animate,
      ...config,
    })
    annotation.show()
  }, [ref, type, color, animate, animationDuration, config])

  return <span ref={ref}>{children}</span>
}

RoughNotationWrapper.propTypes = {
  children: PropTypes.array,
  type: PropTypes.string,
  color: PropTypes.string,
  animate: PropTypes.bool,
  animationDuration: PropTypes.number,
}

````

**Comment by linkstrifer** [comment]
@pom421 which rough-notation version are you using?

**Comment by linkstrifer** [comment]
This will be supported in v0.1.1
