### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by tanvirpiash** [linkstrifer/react-rough-notation#22]
code ERESOLVE
ERESOLVE unable to resolve dependency tree

While resolving: _____-next@undefined
Found: react@17.0.2
node_modules/react
react@"17.0.2" from the root project

Could not resolve dependency:
peer react@"^16.13.1" from react-rough-notation@1.0.1
node_modules/react-rough-notation
react-rough-notation@"*" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

**Comment by linkstrifer** [comment]
I'm workin on it, is related to React 17, I'm using 16 as a dependency so there is a conflict there

**Comment by tanvirpiash** [comment]
> I'm workin on it, is related to React 17, I'm using 16 as a dependency so there is a conflict there

Thanks for the quick response. Can't wait to try the new fixed version. Happy coding. Peace.

**Comment by linkstrifer** [comment]
@tanvirpiash I just released v1.0.2, it should work with React 17 now.
