### ISSUE TITLE
Support for React v18

### ISSUE THREAD

**Issue by tnjsrf** [linkstrifer/react-rough-notation#25]
**Is your feature request related to a problem? Please describe.**
I am using react-rough-notation in my app, and if I update my app to React v18 it will stop working.

**Describe the solution you'd like**
Support for React v18

**Describe alternatives you've considered**
I tried the pure rough-notations, it works. But I would prefer to use a react-wrapper for it.

**Comment by linkstrifer** [comment]
Is throwing an error or something?

The react-rough-notation playground is using React 18.2 without problems, can you give me more information or an online example?

https://codesandbox.io/s/github/linkstrifer/react-rough-notation-playground

**Comment by tnjsrf** [comment]
> 

Looks like the problem is specific to Notation Groups, I've added Notation Groups to the example you have sent. 

https://codesandbox.io/s/tender-goodall-f1v2gx?file=/src/App.js


You can also spot the problem inside `TestRNG` components in your example.

**Comment by Jaival** [comment]
Any updates or possible solutions for the issue?

**Comment by linkstrifer** [comment]
@Jaival can you try the latest beta version?

Let me know if it fixes the issue, I'm still testing it but looks like is working as expected now

[1.0.3-beta.1](https://www.npmjs.com/package/react-rough-notation/v/1.0.3-beta.1)

**Comment by Jaival** [comment]
@linkstrifer I tried the beta version. It is installed properly and the animation runs now, but the animations are running at the same time. I have four highlight animations played one by one (working in v1.0.2) but in beta, they are playing at the same time.

Sandbox Link:
beta version: https://codesandbox.io/s/hero-sandbox-beta-1-0-3-6jqlsq

https://user-images.githubusercontent.com/34303559/181740909-83fda032-1505-4fc0-a00b-2fa980947643.mp4

Sandbox represents the beta version working (issue) and the video represents how it was working V1.0.2.

**Comment by linkstrifer** [comment]
@Jaival I think is working as expected with beta.4

https://codesandbox.io/s/hero-sandbox-beta-1-0-3-forked-bjog9v

what do you think? If it works, I'll publish a new stable version

**Comment by Jaival** [comment]
Yeah, it's working correctly now with my implementation. I checked in the sandbox and on my machine also it working.

**Comment by linkstrifer** [comment]
Fixed on https://github.com/linkstrifer/react-rough-notation/pull/26

**Comment by Jaival** [comment]
I want to ask you if this project is open source? If it is I wanted to learn and contribute to this project. I have contacted you on Twitter, we can continue our conversation there.

**Comment by linkstrifer** [comment]
@Jaival yeah, you can send any PR and I'll review it, is completely open source

**Comment by Jaival** [comment]
Yeah, sure. I am actually a DevOps engineer and I want to learn typescript to add it to my portfolio. I think I can help the project with this todo - Auto compile and publish to npm.
