### ISSUE TITLE
Proposal: use <mark> as default tag

### ISSUE THREAD

**Issue by franky47** [linkstrifer/react-rough-notation#5]
It seems more semantically adapted:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/mark

**Comment by franky47** [comment]
One issue with it though is that it comes with default styles in some browsers, example with an `underline` type, the yellow highlight being the default browser style:
<img width="268" alt="image" src="https://user-images.githubusercontent.com/1174092/83320130-b4062980-a244-11ea-80b9-4617b0228fc7.png">

**Comment by linkstrifer** [comment]
I like the idea to make it semantic but sometimes annotation is just visual styling, maybe a prop to handle this could work, I'm thinking about `semantic={true}` optional with false by default, also overwrite the `<mark>` default styles, what do you think?

**Comment by franky47** [comment]
I did it with global CSS in my case, so it does not translate well for styling-agnostic React components.. It might not be that important actually, as there is the option for those who want to use `mark`.
